config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:registrations, :passwords]

  concern :has_votes do
  	resources :votes, only: :create
  end

  concern :has_questions do
    resources :questions, only: [:new, :create]
  end

  get '/questions/:id/responses/new', to: 'responses#new', as: 'new_question_response'
  get '/questions/:id/responses', to: 'responses#index', as: 'question_responses'
  post '/questions/:id/responses', to: 'responses#create'
  resources :responses, only: [:destroy, :edit, :update]
  put '/responses/:id/approve', to: 'responses#approve', as: 'approve_response'
  put '/responses/:id/disapprove', to: 'responses#disapprove', as: 'disapprove_response'

  resources :questions, only: [:destroy, :edit, :update]
  post '/questions/:id/upvote/', to: 'votes#upvote', as: 'upvote_question'
  put '/questions/:id/approve', to: 'questions#approve', as: 'approve_question'
  put '/questions/:id/disapprove', to: 'questions#disapprove', as: 'disapprove_question'

  get '/events/:id/open', to: 'events#open', as: 'open_event'
  put '/events/:id/open', to: 'events#open', as: 'open_event'

  get '/users', to: 'users#index', as: 'users'
  post '/users/:id', to: 'users#update', as: 'user'
  get '/users/:id/questions', to: 'users#show_questions', as: 'user_questions'
  get '/users/:id/votes', to: 'users#show_votes', as: 'user_votes'

  root 'events#last'
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :user_id, :event_id, presence: true
  validates :copy, presence: true, length: { minimum: 3 }

  belongs_to :user
  belongs_to :events
  has_many :votes, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :friends, dependent: :destroy

  scope :approved_anonymous, -> { where('anonymous_flag IS NULL OR anonymous_flag = false OR (anonymous_flag = true AND admin_approved_at IS NOT NULL)') }

  def upvotes
    votes.where('type_of LIKE ?', :up).count
  end

  def score
    self.upvotes
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:edit, :show, :update, :destroy, :approve, :disapprove]
  before_action :set_event, only: [:new, :create]
  before_action :set_events

  def show
    @user = current_user
  end

  def new
    @question = @event.questions.new
    authorize(@question)
  end

  def create
    if anonymous_enabled? && question_params[:anonymous_flag] == '1'
      @question = @event.questions.create(question_params.merge(event_id: @event.id, user_id: User.find_by(name: 'Anonymous').id))
    else
      @question = @event.questions.create(question_params.merge(event_id: @event.id, user_id: current_user.id))
    end
    authorize(@question)

    if @question.errors.any?
      redirect_to :back, alert: "Error: " + @question.errors.full_messages.to_sentence
    else
      redirect_to event_path(@question.event_id, anchor: "question_#{@question.id}"), notice: 'Question was created.'
    end
  end

  def edit
    authorize(@question)
    @event = @question.event
  end

  def update
    authorize(@question)

    if anonymous_enabled? && question_params[:anonymous_flag] == '1'
      @question.update(question_params.merge(user_id: User.find_by(name: 'Anonymous').id))
    else
      @question.update(question_params)
    end

    if @question.errors.any?
      redirect_to :back, alert: "Error: #{@question.errors.full_messages.to_sentence}"
    else
      redirect_to event_path(@question.event_id, anchor: "question_#{@question.id}"), notice: 'Question was updated.'
    end
  end

  def approve
    authorize(@question)
    @question.update_columns(admin_approved_at: Time.now, admin_approved_by_user_id: current_user.id)
    redirect_to event_path(@question.event_id, anchor: "question_#{@question.id}"), notice: 'Question was approved.'
  end

  def disapprove
    authorize(@question)
    @question.update_columns(admin_approved_at: nil, admin_approved_by_user_id: nil)
    redirect_to event_path(@question.event_id, anchor: "question_#{@question.id}"), notice: 'Question was disapproved.'
  end

  def destroy
    authorize(@question)

    event_id = @question.event_id
    @question.destroy
    redirect_to event_path(event_id), notice: "Question was destroyed."
  end

  private

  def question_params
    params.require(:question).permit(:copy, :anonymous_flag)
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_events
    @events = Event.all
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_edit_form.html.erb
<div class="row Box">
  <div class="small-12 columns">
    <%= form_for @question do |f| %>
    <div class="row u-mb-1">
      <div class="small-12 columns">
        <h4>For Event: <%= f.label :copy, @question.event.name %></h4>
        <div class="floatlabel-wrapper required" style="position:relative">
          <%= f.text_area :copy, placeholder: 'Question', class: 'u-mb-0' %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns u-mb-4" style="text-align:center">
        <p class="small">Please be considerate and respectful when posting questions and responses.</p>
      </div>
    </div>
    <div class="row u-mb-4">
      <div class="small-6 columns">
        <% if anonymous_enabled? %>
        <div class="checkbox">
          <%= f.check_box :anonymous_flag, value: true, onClick: 'if(this.checked) { alert("You’ve chosen to post anonymously. This post will not be publicly visible until approved by an admin.") }' %>
          <span></span>
          <%= f.label :anonymous_flag, 'Anonymous' %>
        </div>
        <% end %>
      </div> 
    <div class="small-1 small-offset-2 columns">
    </div>
    <div class="small-3 columns">
      <% if @_controller.action_name == 'new' %>
      <%= f.submit 'Submit Question', class: "Button Button--green Button--fullWidth" %>
      <% elsif @_controller.action_name == 'edit' %>
      <p><%= f.submit 'Update Question', class: "Button Button--green Button--fullWidth" %></p>
      <p><%= link_to 'Destroy Question', @question, method: :delete, class: "Button Button--outline Button--withIcon Button--red Icon--close Button--fullWidth", data: {:confirm => "Are you sure you want to destroy this question?"} %></p>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/questions/_form.html.erb
<div class="row Box u-mb-5">
  <div class="small-12 columns">
    <%= form_for [@event, @question] do |f| %>
    <div class="row">
      <div class="small-12 columns">
        <h4>For Event: <%= f.label :copy, @event.name %></h4>
      </div>
    </div>
    <div class="row u-mb-1">
      <div class="small-12 columns">
        <div class="floatlabel-wrapper required" style="position:relative">
          <%= f.text_area :copy, placeholder: 'Question', class: 'u-mb-0' %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns u-mb-4" style="text-align:center">
        <p class="small">Please be considerate and respectful when posting questions and responses.</p>
      </div>
    </div>
    <div class="row">
      <div class="small-6 columns">
        <% if anonymous_enabled? %>
        <div class="checkbox">
          <%= f.check_box :anonymous_flag, value: true, onClick: 'if(this.checked) { alert("You’ve chosen to post anonymously. This post will not be publicly visible until approved by an admin.") }' %>
          <span></span>
          <%= f.label :anonymous_flag, 'Anonymous' %>
        </div>
        <% end%>
      </div>
      <div class="small-1 small-offset-2 columns">
      </div>
      <div class="small-3 columns">
        <%= f.submit 'Submit Question', class: "Button Button--green Button--fullWidth" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/_question.html.erb
  <% if params[:question] == question.id.to_s %>
<div class="row u-dividerTopSmall u-mb-5 is-active" id="question_<%= question.id.to_s %>">
  <% else %>
<div class="row u-dividerTopSmall u-mb-5" id="question_<%= question.id.to_s %>">
  <% end %>
  <div class="small-1 columns">
    <% if question.anonymous_flag %>
      <%= image_tag 'anonymous.png', class: 'profile-image' %>
    <% else %>
      <%= image_tag question.user.image_url, class: 'profile-image' %>
    <% end %>
  </div>
  <div class="small-11 columns <%= question.anonymous_flag && anonymous_approval_required? && !question.admin_approved_at ? 'anonymous_unapproved' : '' %>">
    <div class="row u-mb-2">
      <div class="small-12 columns">
        <span class="Ticket-reply">
          <%= link_to "#{question.user.name}", user_questions_path(question.user.id) %> asks:
        </span>
        <span class="Ticket-timestamp" data-toggle="tooltip" data-placement="top" title="<%= question.created_at %>"><%= time_ago_in_words(question.created_at) %> ago</span>
      </div>
    </div>
    <div class="row u-mb-2">
      <div class="small-11 columns">
        <%= simple_format(question.copy) %>
        <% if question.updated_at != question.created_at %>
          <p class="small">Last edited at: <%= question.updated_at %></p>
        <% end %>
        <% if question.admin_approved_at %>
          <p class="small">Approved at: <%= question.admin_approved_at %></p>
        <% end %>        
      </div>
      <div class="small-1 columns u-textAlignCenter">
        <div class="row u-mb-2">
          <span class="Badge"><%= question.score %></span>
          <% if @user.votes.where("question_id = ?", question.id).where("type_of LIKE ?", 'up').empty? %>
          <%= link_to '', upvote_question_path(question.id), { method: :post, class: 'Button Button--outline Button--green Button--icon Icon--arrowUp', :'data-toggle' => 'tooltip', :'data-placement' => 'top', title: 'Upvote' } %>
          <% else %>
          <a class="Button Button--green Button--icon Icon--arrowUp"></a>
          <% end %>
        </div>
        <div class="row u-mb-2">
          <p></p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="small-8 columns">
        <p class="small">
            <% if !current_page?(url_for(:controller => 'users', :action => 'show_questions')) && !current_page?(url_for(:controller => 'users', :action => 'show_votes')) %>
          <% if policy(question).edit? %>
          <%= link_to 'Edit Question', edit_question_path(question.id), class: "u-mr-2" %>
          <% end %>
          <% end %>
          <% if question.responses.count > 0 %>
          <%= link_to "View #{'response'.pluralize(question.responses.count)} (#{question.responses.count.to_s})", question_responses_path(question.id), class: "u-mr-2" %>
          <% end %>
          <%= link_to 'Post a response', new_question_response_path(question.id) %>
        </p>
      </div>
    </div>      
    <% if !current_page?(url_for(:controller => 'users', :action => 'show_questions')) && !current_page?(url_for(:controller => 'users', :action => 'show_votes')) %>
      <% if policy(question).destroy? && current_user.admin %>
    <div class="row">
      <div class="small-8 columns">
      </div>
      <div class="small-4 columns">
        <p class="small"><%= link_to '[Admin: Destroy Question]', question_path(question.id), method: :delete, data: {:confirm => "Are you sure you want to destroy this question?"} %></p>
      </div>
    </div>
      <% end %>
    <% end %>
    <% if question.anonymous_flag && anonymous_approval_required? && current_user.admin %>
    <div class="row">
      <div class="small-6 columns">
      </div>
      <div class="small-6 columns">
        <p class="small">
        <% if question.admin_approved_at %>
          <%= link_to '[Admin: Disapprove Anonymous Question]', disapprove_question_path(question.id), method: :put, data: {:confirm => "Are you sure you want to disapprove this question?"} %>
        <% else %>
          <%= link_to '[Admin: Approve Anonymous Question]', approve_question_path(question.id), method: :put, data: {:confirm => "Are you sure you want to approve this question?"} %>
        <% end %>
        </p>
      </div>
    </div>
    <% end %>    
  </div>
</div>

app/views/questions/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>Edit Question</h2>
  </div>
</div>

<%= render 'edit_form' %>

app/views/questions/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>Submit a Question</h2>
  </div>
</div>

 <%= render 'form' %>

app/views/questions/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>View Question</h2>
  </div>
</div>
<%= render @question %>