config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:registrations, :passwords]

  concern :has_votes do
  	resources :votes, only: :create
  end

  concern :has_questions do
    resources :questions, only: [:new, :create]
  end

  get '/questions/:id/responses/new', to: 'responses#new', as: 'new_question_response'
  get '/questions/:id/responses', to: 'responses#index', as: 'question_responses'
  post '/questions/:id/responses', to: 'responses#create'
  resources :responses, only: [:destroy, :edit, :update]
  put '/responses/:id/approve', to: 'responses#approve', as: 'approve_response'
  put '/responses/:id/disapprove', to: 'responses#disapprove', as: 'disapprove_response'

  resources :questions, only: [:destroy, :edit, :update]
  post '/questions/:id/upvote/', to: 'votes#upvote', as: 'upvote_question'
  put '/questions/:id/approve', to: 'questions#approve', as: 'approve_question'
  put '/questions/:id/disapprove', to: 'questions#disapprove', as: 'disapprove_question'

  get '/events/:id/open', to: 'events#open', as: 'open_event'
  put '/events/:id/open', to: 'events#open', as: 'open_event'

  get '/users', to: 'users#index', as: 'users'
  post '/users/:id', to: 'users#update', as: 'user'
  get '/users/:id/questions', to: 'users#show_questions', as: 'user_questions'
  get '/users/:id/votes', to: 'users#show_votes', as: 'user_votes'

  root 'events#last'
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :user_id, :name, presence: true
  has_many :questions, dependent: :destroy
  belongs_to :user

  scope :interleaved_scheduled,
    ->{ order('CASE WHEN scheduled_at IS NOT NULL THEN scheduled_at ELSE created_at END') }

  def close
    update(closed: true)
  end

  def open
    update(closed: false)
  end

  # closed? overloaded to return true if event was manually closed, or if the scheduled time has been reached
  def closed?
    if scheduled_at.present?
      DateTime.now > scheduled_at
    else
      closed   # manually closed?
    end
  end

  def vote_count
    questions.inject(0) { |result, question| result += question.votes.size }
  end

  def participants
    (questioner_user_ids + voter_user_ids).uniq
  end

  # participant_count is the number of unique users who have submitted a question or a vote
  def participant_count
    participants.count
  end

  def questioner_user_ids
    questions.map { |question| question.user_id }
  end

  def voter_user_ids
    questions.inject([]) do |result, question|
      result += question.votes.map(&:user_id)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :show, :update, :destroy, :close, :open]
  before_action :set_events

  def index
    set_users_questions_votes_count # for stat summary
  end

  # most recently created
  def last
    if @events.empty?
      redirect_to events_path
    elsif @events.last.closed?
      redirect_to events_path
    else
      redirect_to event_path(@events.last)
    end
  end

  def show
    @user = current_user

    @questions = @event.questions
    @unapproved_anonymous_questions_count = @questions.where('anonymous_flag = true AND admin_approved_at IS NULL').count
    if anonymous_requires_admin_approval? && !@user.admin
      @questions = @questions.approved_anonymous
    end
    if params[:sort] == 'date' # reverse chronological
      @questions = @questions.reverse
    else
      @questions = @questions.sort_by(&:score).reverse  # popularity by default
    end
  end

  def new
    @event = Event.new
    authorize(@event)
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    authorize(@event)
    @event.save

    if @event.errors.any?
      render :new, alert: "Error: " + @event.errors.full_messages.to_sentence
    else
      redirect_to events_path, notice: "Event (#{@event.name}) was created."
    end
  end

  def edit
    authorize @event
  end

  def update
    authorize @event

    @event.update(event_params)

    if @event.errors.any?
      redirect_to :back, alert: "Error: " + @event.errors.full_messages.to_sentence
    else
      redirect_to @event, notice: 'Event was updated.'
    end
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to events_path, notice: 'Event was deleted.'
  end

  def close
    authorize @event
    @event.close
    redirect_to :back, notice: 'Event was closed.'
  end

  def open
    authorize @event
    @event.open
    redirect_to :back, notice: 'Event was opened.'
  end


  private

  def event_params
    params.require(:event).permit(:name, :scheduled_at, :description)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def set_events
    @events = Event.interleaved_scheduled.page(params[:page]).per(20)
  end

  def set_users_questions_votes_count
    @users_count = User.count
    @questions_count = Question.count
    @votes_count = Vote.count
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def format_datetime(event_datetime)
    if event_datetime.present?
      event_datetime.strftime('%B %d, %Y at %-l:%M%p')
    end
  end

  def relative_time_to_event(event)
    if !event.closed? && !event.scheduled_at.nil?
      distance_of_time_in_words(DateTime.now, event.scheduled_at)
    end
  end

  def descending_events(events)
    events.reverse_order
  end
end

app/views/events/_form.html.erb
<div class="row Box">
  <div class="small-12 columns">
    <%= form_for @event do |f| %>
    <div class="row u-mb-1">
      <div class="small-12 columns">
        <div class="floatlabel-wrapper required" style="position:relative">
          <%= f.text_field :name, placeholder: 'Name' %>
          <%= f.text_field :scheduled_at, placeholder: 'Date and Time' %>
          <%= f.text_area :description, placeholder: 'Description'%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="small-6 columns">
      </div>
      <div class="small-1 small-offset-2 columns">
      </div>
      <div class="small-3 columns">
      <% if @_controller.action_name == 'edit' %>
        <p><%= f.submit 'Update Event', class: "Button Button--green Button--fullWidth" %></p>
        <p><%= link_to 'Destroy Event', @event, method: :delete, class: "Button Button--outline Button--withIcon Button--red Icon--close Button--fullWidth", data: {:confirm => "Are you sure you want to destroy this event?"} %></p>
      <% else %>
        <%= f.submit 'Create Event', class: "Button Button--green Button--fullWidth" %>
      <% end %>
      </div>
    <% end %>
    </div>
  </div>
</div>

<script>
      $(function () {
        $('#event_scheduled_at').fdatepicker({
          format: 'yyyy-mm-dd hh:ii',
          disableDblClickSelection: true,
          pickTime: true
        });
      })
      </script>

app/views/events/_sidebar.html.erb
<div class="small-3 columns">
  <nav class="SideNav">
    <h3>Pick an event</h3>
    <ul>
    <% descending_events(@events).first(10).each do |event| %>
      <% if @event.nil? %>
      <li><%= link_to event.name, event_path(event.id) %></li>
      <% else %>
        <% if event.id == @event.id %>
      <li class="is-active"><%= link_to event.name, event_path(event.id) %></li>
        <% else %>
      <li><%= link_to event.name, event_path(event.id) %></li>
        <% end %>
      <% end %>
    <% end %>
    <% if current_page?(url_for(:controller => 'events', :action => 'index')) %>
      <li class='is-active'><%= link_to 'Show All', events_path %></li>
    <% else %>
      <li><%= link_to 'Show All', events_path %></li>
    <% end %>
    </ul>


    <% if !@event.nil? %>
    <% if !@event.id.nil? %>
    <ul>
    <% if params[:sort] == 'date' %>
      <li><%= link_to 'Sort by popularity', event_path(@event.id) %></li>
      <li class="is-active"><%= link_to 'Sort by date', event_path(@event.id, sort: 'date') %></li>
    <% else %>
      <li class="is-active"><%= link_to 'Sort by popularity', event_path(@event.id) %></li>
      <li><%= link_to 'Sort by date', event_path(@event.id, sort: 'date') %></li>
    <% end %>
    </ul>
    <% end %>
    <% end %>

    <h3>Your stats:</h3>
    <ul>
      <li><%= "#{current_user.votes.count} #{'vote'.pluralize(current_user.votes.count)}" %></li>
      <li><%= link_to "#{current_user.questions.count} #{'question'.pluralize(current_user.questions.count)}", user_questions_path(current_user.id)%></li>
    </ul>
    <% if policy(@events).create? %>
    <h3>Admin</h3>
    <ul>
      <li><%= link_to 'Create Event', new_event_path %></li>
      <li><%= link_to 'Manage Users', users_path %></li>
    </ul>
    <% end %>
    <h3>Session</h3>
    <ul>
      <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
    </ul>
  </nav>
</div>

app/views/events/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>Edit Event</h2>
  </div>
</div>

<%= render 'form' %>

app/views/events/index.html.erb
<div class="row u-mb-3">
  <div class="small-6 columns">
    <h2>Events</h2>
  </div>
  <% if policy(@events).create? %>
  <div class="small-2 small-offset-4 columns">
    <%= link_to 'Create Event', new_event_path, class: 'Button Button--green Button--fullWidth'%>
  </div>
  <% end %>
</div>
<div class="row u-mb-2">
  <div class="small-12 columns">
    <p><%= "#{pluralize(@users_count, 'person')} have submitted #{pluralize(@questions_count, 'question')} and cast #{pluralize(@votes_count, 'vote')}" %></p>
  </div>
</div>

<div class="row u-mb-4 u-dividerTopSmall">
  <div class="small-12 columns">
  <% if @events.empty? %>
  <h3>There are no events yet. Ask an admin to create one</h3>
  <% end %>
  <table class="u-mb-5">
    <tbody class="Table-actions" id='event_table'>
    <% descending_events(@events).each do |event| %>
      <tr class="event-item" id="<%= "event_index_#{event.id}" %>">
        <td>
          <div class="Table-actions">
          <h3 class="name"><%= link_to event.name, event_path(event.id) %></h3>
          <% if event.closed? %>
          <span class="Badge">Closed</span>
          <% end %>
          <div>
            <p class="small datetime">
              <%= format_datetime(event.scheduled_at) %>
            </p>
          </div>
          <p class="description"><%= event.description %></p>
          <p class="small"><%= "#{pluralize(event.vote_count, 'vote')} on #{pluralize(event.questions.size, 'question')} from #{pluralize(event.participant_count, 'person')}." %></p>
            <div class="ButtonGroup">
            <% if policy(@events).edit? %>
              <%= link_to '', edit_event_path(event.id), { class: 'Button Button--blue Button--icon Icon--gear', :'data-toggle' => 'tooltip', :'data-placement' => 'top', title: 'Edit Event' }%>
            <% end %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @events %>
</div>
</div>

app/views/events/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>New Event</h2>
  </div>
</div>

<%= render 'form' %>

app/views/events/show.html.erb
<div class="row">
  <div class="small-10 columns">
    <h2 id='event_name'><%= @event.name %>
    <% if @event.closed? %>
    <span class="Badge Badge--uppercase Badge--grey">Closed</span>
    <% end %>
    </h2>
  </div>
  <div class="small-2 columns">
    <p>
    <% if !@event.closed? %>
    <%= link_to 'Ask Question', new_event_question_path(@event.id), class: 'Button Button--green Button--fullWidth'%>
    <% else %>
    <a class="Button is-disabled Button--green Button--fullWidth" data-toggle="tooltip" data-placement="top" title="Event is closed">Ask Question</a>
    <% end %>
    </p>
  </div>
</div>
    <div class="row u-mb-3 event_header">
      <div class="small-10 columns">
      <div><p id='event_datetime' class="small"><%= format_datetime(@event.scheduled_at) %></p></div>
    <p id='event_description'><%= @event.description %></p>
      </div>
        <% if policy(@event).edit? %>
              <div class="small-2 columns u-textAlignRight">
    <% if @event.scheduled_at.nil? %>
      <% if @event.closed? %>
        <%= link_to '', open_event_path, { class: 'Button Button--green Button--icon Icon--arrowUp', :'data-toggle' => 'tooltip', :'data-placement' => 'top', title: 'Open Event' }%>
      <% else %>
        <%= link_to '', close_event_path, { class: 'Button Button--red Button--icon Icon--arrowDown', :'data-toggle' => 'tooltip', :'data-placement' => 'top', title: 'Close Event' }%>
      <% end %>
    <% end %>
    <%= link_to '', edit_event_path, { class: 'Button Button--blue Button--icon Icon--gear', :'data-toggle' => 'tooltip', :'data-placement' => 'top', title: 'Edit Event' } %>
  </div>
  <% end %>
    </div>
<div class="row u-mb-4">
  <div class="small-12 columns">
    <p class="small"><%= "#{pluralize(@event.vote_count, 'vote')} on #{pluralize(@event.questions.size, 'question')} from #{pluralize(@event.participant_count, 'person')}." %></p>
    <% if anonymous_approval_required? %>
    <p class="small">This event has <%= @unapproved_anonymous_questions_count %> unapproved anonymous questions.</p>
    <% end %>
  </div>
</div>
<% if @event.questions.size == 0 %>
<div class="row u-mb-2">
  <div class="small-12 columns">
  <h3>There are no questions in this event yet. Ask one!</h3>
  </div>
</div>
<% end %>

<%= render @questions %>