config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:registrations, :passwords]

  concern :has_votes do
  	resources :votes, only: :create
  end

  concern :has_questions do
    resources :questions, only: [:new, :create]
  end

  get '/questions/:id/responses/new', to: 'responses#new', as: 'new_question_response'
  get '/questions/:id/responses', to: 'responses#index', as: 'question_responses'
  post '/questions/:id/responses', to: 'responses#create'
  resources :responses, only: [:destroy, :edit, :update]
  put '/responses/:id/approve', to: 'responses#approve', as: 'approve_response'
  put '/responses/:id/disapprove', to: 'responses#disapprove', as: 'disapprove_response'

  resources :questions, only: [:destroy, :edit, :update]
  post '/questions/:id/upvote/', to: 'votes#upvote', as: 'upvote_question'
  put '/questions/:id/approve', to: 'questions#approve', as: 'approve_question'
  put '/questions/:id/disapprove', to: 'questions#disapprove', as: 'disapprove_question'

  get '/events/:id/open', to: 'events#open', as: 'open_event'
  put '/events/:id/open', to: 'events#open', as: 'open_event'

  get '/users', to: 'users#index', as: 'users'
  post '/users/:id', to: 'users#update', as: 'user'
  get '/users/:id/questions', to: 'users#show_questions', as: 'user_questions'
  get '/users/:id/votes', to: 'users#show_votes', as: 'user_votes'

  root 'events#last'
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:edit, :update, :destroy, :approve, :disapprove]
  before_action :set_question, only: [:index, :new, :create]
  before_action :set_events

  def index
    @user = current_user

    @responses = @question.responses
    @unapproved_anonymous_responses_count = @responses.where('anonymous_flag = true AND admin_approved_at IS NULL').count
    if anonymous_requires_admin_approval? && !@user.admin
      @responses = @responses.approved_anonymous
    end
    @responses = @responses.sort_by(&:created_at)

    @event = @question.event
  end

  def new
    @user = current_user
    @event = @question.event
    @responses = @question.responses.sort_by(&:created_at) # load existing responses
    @response = @question.responses.new
  end

  def create
    if anonymous_enabled? && response_params[:anonymous_flag] == '1'
      @response = @question.responses.create(response_params.merge(question_id: @question.id, user_id: User.find_by(name: 'Anonymous').id))
    else
      @response = @question.responses.create(response_params.merge(question_id: @question.id, user_id: current_user.id))
    end

    if @response.errors.any?
      redirect_to :back, alert: "Error: " + @response.errors.full_messages.to_sentence
    else
      redirect_to question_responses_path(@question.id, anchor: "response_#{@response.id}"), notice: 'Response was created.'
    end
  end

  def destroy
    authorize(@response)

    question_id = @response.question_id
    @response.destroy
    redirect_to question_responses_path(question_id), notice: "Response was destroyed."
  end

  def edit
    authorize(@response)
    @question = @response.question
    @event = @question.event
    @user = @response.user
    @responses = @question.responses
  end

  def update
    authorize(@response)
    if anonymous_enabled? && response_params[:anonymous_flag] == '1'
      @response.update(response_params.merge(user_id: User.find_by(name: 'Anonymous').id))
    else
      @response.update(response_params)
    end

    if @response.errors.any?
      redirect_to :back, alert: "Error: #{@response.errors.full_messages.to_sentence}"
    else
      redirect_to question_responses_path(@response.question_id, anchor: "response_#{@response.id}"), notice: 'Response was updated.'
    end
  end

  def approve
    authorize(@response)
    @response.update_columns(admin_approved_at: Time.now, admin_approved_by_user_id: current_user.id)
    redirect_to question_responses_path(@response.question_id, anchor: "response_#{@response.id}"), notice: 'Response was approved.'
  end

  def disapprove
    authorize(@response)
    @response.update_columns(admin_approved_at: nil, admin_approved_by_user_id: nil)
    redirect_to question_responses_path(@response.question_id, anchor: "response_#{@response.id}"), notice: 'Response was disapproved.'
  end

  private

  def response_params
    params.require(:response).permit(:copy, :anonymous_flag)
  end

  def set_response
    @response = Response.find(params[:id])
  end

  def set_question
    if anonymous_requires_admin_approval? && !current_user.admin
      @question = Question.approved_anonymous.find(params[:id])
    else
      @question = Question.find(params[:id])
    end
  end

  def set_events
    @events = Event.all
  end
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_edit_form.html.erb
<div class="row">
<div class="small-11 small-offset-1 columns">
<div class="row Box u-mb-5">
  <div class="small-12 columns">
    <%= form_for @response do |f| %>
    <div class="row u-mb-1">
      <div class="small-12 columns">
        <div class="floatlabel-wrapper required" style="position:relative">
          <%= f.text_area :copy, placeholder: 'Response', class: 'u-mb-0' %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns u-mb-4" style="text-align:center">
        <p class="small">Please be considerate and respectful when posting questions and responses.</p>
      </div>
    </div>
    <div class="row">
      <div class="small-6 columns">
        <% if anonymous_enabled? %>
        <div class="checkbox">
          <%= f.check_box :anonymous_flag, value: true, onClick: 'if(this.checked) { alert("You’ve chosen to post anonymously. This post will not be publicly visible until approved by an admin.") }' %>
          <span></span>
          <%= f.label :anonymous_flag, 'Anonymous' %>
        </div>
        <% end %>
      </div>
    <div class="small-1 small-offset-2 columns">
    </div>
    <div class="small-3 columns">
      <p><%= f.submit 'Edit Response', class: "Button Button--green Button--fullWidth" %></p>
      <p><%= link_to 'Destroy Response', @response, method: :delete, class: "Button Button--outline Button--withIcon Button--red Icon--close Button--fullWidth", data: {:confirm => "Are you sure you want to destroy this response?"} %></p>
    </div>
    </div>
    <% end %>
  </div>
</div>
</div>
</div>

app/views/responses/_form.html.erb
<div class="row">
  <div class="small-11 small-offset-1 columns">
    <div class="row Box u-mb-5">
      <div class="small-12 columns">
        <%= form_for [@question, @response] do |f| %>
        <div class="row u-mb-1">
          <div class="small-12 columns">
            <div class="floatlabel-wrapper required" style="position:relative">
              <%= f.text_area :copy, placeholder: 'Response', class: 'u-mb-0' %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="small-12 columns u-mb-4" style="text-align:center">
            <p class="small">Please be considerate and respectful when posting questions and responses.</p>
          </div>
        </div>
        <div class="row">
          <div class="small-6 columns">
            <% if anonymous_enabled? %>
            <div class="checkbox">
              <%= f.check_box :anonymous_flag, value: true, onClick: 'if(this.checked) { alert("You’ve chosen to post anonymously. This post will not be publicly visible until approved by an admin.") }' %>
              <span></span>
              <%= f.label :anonymous_flag, 'Anonymous' %>
            </div>
            <% end %>
          </div>
          <div class="small-1 small-offset-2 columns">
          </div>
          <div class="small-3 columns">
            <%= f.submit 'Submit Response', class: "Button Button--green Button--fullWidth" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/responses/_response.html.erb
<% if !response.id.nil? %> <%# don't render new response %>
  <% if params[:response] == response.id.to_s %>
<div class="row u-dividerTopSmall u-mb-4 is-active" id="response_<%= response.id.to_s %>">
  <% else %>
<div class="row u-dividerTopSmall u-mb-4" id="response_<%= response.id.to_s %>">
  <% end %>
  <div class="small-11 small-offset-1 columns <%= response.anonymous_flag && anonymous_approval_required? && !response.admin_approved_at ? 'anonymous_unapproved' : '' %>">
    <div class="small-1 columns">
      <% if response.anonymous_flag %>
        <%= image_tag 'anonymous.png', class: 'profile-image' %>
      <% else %>
        <%= image_tag response.user.image_url, class: 'profile-image' %>
      <% end %>
    </div>
    <div class="small-11 columns">
      <div class="row u-mb-2">
        <span class="Ticket-reply">
          <%= link_to "#{response.user.name}", user_questions_path(response.user.id) %> responds:
        </span>
        <span class="Ticket-timestamp" data-toggle="tooltip" data-placement="top" title="<%= response.created_at %>"><%= time_ago_in_words(response.created_at) %> ago</span>
      </div>
      <div class="row u-mb-3">
        <%= simple_format(response.copy) %>
        <% if response.updated_at != response.created_at %>
          <p class="small">Last edited at: <%= response.updated_at %></p>
        <% end %>
        <% if response.admin_approved_at %>
          <p class="small">Approved at: <%= response.admin_approved_at %></p>
        <% end %>
      </div>
      <div class="row u-mb-2">
        <p class="small">
          <% if policy(response).edit? %>
            <%= link_to 'Edit Response', edit_response_path(response.id) %>
          <% end %>
          <% if policy(response).destroy? && current_user.admin %>
            <%= link_to '[Admin: Destroy Response]', response_path(response.id), method: :delete, data: { :confirm => "Are you sure you want to destroy this response?" } %>
          <% end %>
        </p>
      </div>
      <% if response.anonymous_flag && anonymous_approval_required? && current_user.admin %>
      <div class="row u-mb-2">
        <p class="small">
          <% if response.admin_approved_at %>
            <%= link_to '[Admin: Disapprove Anonymous Response]', disapprove_response_path(response.id), method: :put, data: {:confirm => "Are you sure you want to disapprove this response?" } %>
          <% else %>
            <%= link_to '[Admin: Approve Anonymous Response]', approve_response_path(response.id), method: :put, data: { :confirm => "Are you sure you want to approve this response?" } %>
          <% end %>
        </p>
      </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/responses/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>Edit Response</h2>
  </div>
</div>

<%= render @question %>
<%= render 'edit_form' %>
<% if @question.responses.count > 0 %>
  <%= render @responses %>
<% end %>

app/views/responses/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>View Responses</h2>
  </div>
</div>
<%= render @question %>
<% if anonymous_approval_required? %>
<p class="small">This question has <%= @unapproved_anonymous_responses_count %> unapproved anonymous responses.</p>
<% end %>
<%= render @responses %>

app/views/responses/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>Submit Response</h2>
  </div>
</div>
<%= render @question %>
<%= render 'form' %>
<% if @question.responses.count > 0 %>
  <%= render @responses %>
<% end %>